#!/usr/bin/env python
#
# Autogenerated by Thrift Compiler (0.9.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

import sys
import pprint
from urlparse import urlparse
from thrift.transport import TTransport
from thrift.transport import TSocket
from thrift.transport import THttpClient
from thrift.protocol import TCompactProtocol

import AppRpcService
from ttypes import *


class AppRpcServiceClient():
    host = 'localhost'

    client = None
    transport = None

    def __init__(self, cport=None):
        if cport != None:
            self.port = cport
        socket = TSocket.TSocket(self.host, self.port)
        self.transport = TTransport.TFramedTransport(socket)

        protocol = TCompactProtocol.TCompactProtocol(self.transport)
        self.client = AppRpcService.Client(protocol)
        self.transport.open()

    def Close(self):
        self.transport.close()
    def startApp(self, appMessage):
        res = self.client.startApp(appMessage)
        return res
    def stopApp(self, appMessage):
        res = self.client.stopApp(appMessage)
        return res



